{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ts",
    "module": "bindid",
    "version": "1.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bindid-1.18.0.aar",
          "url": "bindid-1.18.0.aar",
          "size": 328225,
          "sha512": "4ea93c18ee7776e8d4b93ff8d0a4d2d807e1aaaf7adda95759745ed98b99609725a20224516510883b48df9ad4bbc97181cb442979b0c1e38c73067e7bfbac64",
          "sha256": "8a539462affdcd9454b2924a66c14730337fb36a8279310af0f527b60882212b",
          "sha1": "7b01885ca79bd5d1afb53ce684aec98d640ec89c",
          "md5": "6db63567deab6057ee74cb19b0ea429a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.7.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-identity-credential",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "bindid-1.18.0.aar",
          "url": "bindid-1.18.0.aar",
          "size": 328225,
          "sha512": "4ea93c18ee7776e8d4b93ff8d0a4d2d807e1aaaf7adda95759745ed98b99609725a20224516510883b48df9ad4bbc97181cb442979b0c1e38c73067e7bfbac64",
          "sha256": "8a539462affdcd9454b2924a66c14730337fb36a8279310af0f527b60882212b",
          "sha1": "7b01885ca79bd5d1afb53ce684aec98d640ec89c",
          "md5": "6db63567deab6057ee74cb19b0ea429a"
        }
      ]
    }
  ]
}
